openapi: 3.0.3
info:
  title: Role Management API - Director Role Extension
  description: API endpoints for managing Director role assignments and validations
  version: 1.0.0

paths:
  /api/users/{userId}/role:
    get:
      summary: Get user role information
      description: Retrieve current role and permissions for a specific user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: User ID to get role information for
      responses:
        200:
          description: User role information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      userId:
                        type: string
                        format: uuid
                      role:
                        type: string
                        enum: [staff, manager, director]
                      permissions:
                        type: array
                        items:
                          type: string
                        example:
                          ["reports:full", "users:full", "inventory:read"]
                      stationId:
                        type: string
                        format: uuid
                      isActive:
                        type: boolean
        401:
          description: Unauthorized - Invalid or missing authentication
        403:
          description: Forbidden - Insufficient permissions to view role information
        404:
          description: User not found

    patch:
      summary: Update user role
      description: Assign or change a user's role (requires Director or Manager permissions)
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - role
              properties:
                role:
                  type: string
                  enum: [staff, manager, director]
                  description: New role to assign to the user
      responses:
        200:
          description: Role updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      userId:
                        type: string
                        format: uuid
                      oldRole:
                        type: string
                        enum: [staff, manager, director]
                      newRole:
                        type: string
                        enum: [staff, manager, director]
                      updatedAt:
                        type: string
                        format: date-time
        400:
          description: Bad request - Invalid role or business rule violation
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  error:
                    type: string
                    examples:
                      minimum_director: "Cannot remove last Director role"
                      invalid_role: "Invalid role specified"
        401:
          description: Unauthorized
        403:
          description: Forbidden - Insufficient permissions to modify roles

  /api/auth/permissions:
    get:
      summary: Get current user permissions
      description: Retrieve permission matrix for the authenticated user
      responses:
        200:
          description: Permissions retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      userId:
                        type: string
                        format: uuid
                      role:
                        type: string
                        enum: [staff, manager, director]
                      permissions:
                        type: array
                        items:
                          type: string
                        example:
                          ["reports:full", "inventory:read", "users:full"]
                      canAccess:
                        type: object
                        properties:
                          reports:
                            type: object
                            properties:
                              read:
                                type: boolean
                              write:
                                type: boolean
                              export:
                                type: boolean
                          inventory:
                            type: object
                            properties:
                              read:
                                type: boolean
                              write:
                                type: boolean
                          sales:
                            type: object
                            properties:
                              read:
                                type: boolean
                              write:
                                type: boolean
                          users:
                            type: object
                            properties:
                              read:
                                type: boolean
                              write:
                                type: boolean
                              role_assign:
                                type: boolean
        401:
          description: Unauthorized

  /api/admin/minimum-directors/check:
    get:
      summary: Check minimum Director policy
      description: Verify if minimum Director count policy is satisfied
      responses:
        200:
          description: Minimum Director policy status
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      currentDirectorCount:
                        type: integer
                        minimum: 0
                      minimumRequired:
                        type: integer
                        example: 1
                      canModifyRoles:
                        type: boolean
                        description: Whether Director roles can be safely modified
                      activeDirectors:
                        type: array
                        items:
                          type: object
                          properties:
                            userId:
                              type: string
                              format: uuid
                            username:
                              type: string
                            stationId:
                              type: string
                              format: uuid
        401:
          description: Unauthorized
        403:
          description: Forbidden - Only Directors can check this policy

components:
  securitySchemes:
    ClerkAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - ClerkAuth: []
