openapi: 3.0.0
info:
  title: Theme API
  version: 1.0.0
  description: API for managing theme settings.
paths:
  /api/theme:
    get:
      summary: Get theme settings
      description: Retrieves the theme settings for the current station.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThemeSettings'
        '401':
          description: Unauthorized
        '404':
          description: Theme settings not found
    post:
      summary: Create or update theme settings
      description: Creates or updates the theme settings for the current station.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ThemeSettings'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThemeSettings'
        '400':
          description: Bad request
        '401':
          description: Unauthorized

components:
  schemas:
    ThemeSettings:
      type: object
      properties:
        mode:
          type: string
          enum: [light, dark]
        primaryColor:
          type: string
          format: color
          example: '#3B82F6'
